### ISSUE TITLE
[object HTMLDivElement] in Likert Block

### ISSUE THREAD

**Issue by anishapant21** [lattln/mie-form-builder#2]
Steps to replicate:
- Drag and drop the Likert block
- Remove the existing question
- Add new question

Screenshots:

<img width="971" alt="Screenshot 2024-08-03 at 6 37 19 PM" src="https://github.com/user-attachments/assets/745582a3-dde5-40c3-b53a-e465572e1255">

**Comment by lattln** [comment]
solved with v.2.3.11 hotfix
